name: Download assets
on:
  push:
    branches:
      - main

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download a file
        run: curl https://github.com/Zo-Bro-23/Zo-Bro-23/raw/main/README.md -o ./assets/readme.md
      - uses: stefanzweifel/git-auto-commit-action@v4