name: Download assets
on:
  push:
    branches:
      - main

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download a file
        run: curl "https://githubusercontent.zohan.tech?user=Zo-Bro-23&repo=Zo-Bro-23&path=README.md" -o ./assets/readme.md
      - uses: stefanzweifel/git-auto-commit-action@v4